language: elixir

elixir:
  - 1.9

otp_release:
  - 22.0

services:
  - docker

before_install:
  - docker pull rabbitmq:3
  - docker run -d -p 5672:5672 rabbitmq:3."
  - docker ps -a

jobs:
  include:
    - stage: lint
      script: mix credo --strict
    - stage: test
      script: MIX_ENV=test mix test